- name: create caddy2 group
  group:
    name: "{{ caddy2_user }}"
    state: present

- name: create caddy2 user
  user:
    name: "{{ caddy2_user }}"
    group: "{{ caddy2_user }}"
    createhome: true

- name: create needed dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ caddy2_user }}"
  with_items:
    - /var/lib/caddy2
    - /etc/caddy2

- name: Create Caddyfile
  copy:
    content="{{ caddy2_config }}" dest="/etc/caddy2/Caddyfile" owner={{
    caddy2_user }}
  notify: restart caddy2

- name: Create Caddy json config
  copy:
    content="{{ caddy2_config_json }}" dest="/etc/caddy2/config.json" owner={{
    caddy2_user }}
  notify: restart caddy2
  when: caddy2_config_json is defined

- name: fetch caddy
  unarchive:
    src:
      https://github.com/caddyserver/caddy/releases/download/v{{ caddy2_version
      }}/caddy_{{ caddy2_version }}_linux_amd64.tar.gz
    dest: /home/caddy2
    remote_src: yes
    mode: 0755
  register: fetch
  notify:
    - restart caddy2

# we want to leave the original file, otherwise above will think we need to re-run
# the process
- name: copy to caddy2
  command: cp /home/caddy2/caddy {{ caddy2_binary }}
  when: fetch.changed

- name: caddy2 service file
  template: src=caddy2.service.j2 dest=/etc/systemd/system/caddy2.service
  notify:
    - restart caddy2
    - reload systemd

- name: start caddy2
  service: name=caddy2 state=started enabled=yes
